# This is a basic workflow to help you get started with Actions

name: ZIP File Consumer

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  paths:
    - files/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: files/consumer.py
          dest:  consumer.zip
